[project]
name = "violation_checker"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
  "confluent-kafka>=2.12.2",
  "opencv-python>=4.12.0.88",
  "shared",
  "controller"
]

[tool.uv.sources]
shared = { workspace = true }
controller = { workspace = true }