[project]
name = "streaming"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
  "confluent-kafka>=2.12.2",
  "flask>=3.1.2",
  "flask-socketio>=5.5.1",
  "shared",
]

[tool.uv.sources]
shared = { workspace = true }