[project]
name = "controller"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
  "data",
  "shared",
  "opencv-python>=4.12.0.88"
]

[tool.uv.sources]
data = { workspace = true }
shared = { workspace = true }